name: Install Python with uv
description: |
  This GitHub Action installs Python using the uv tool.
  It pins the specified Python version, caches uv files, and installs dependencies.

inputs:
  python-version:
    description: Python version
    required: true
  uv-version:
    description: uv tool version
    required: true

runs:
  using: composite

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        version: ${{ inputs.uv-version }}
        python-version: ${{ inputs.python-version }}

    - name: Install Dependencies
      run: uv sync --frozen
      shell: bash

    - name: Activate venv
      run: |
        uv venv
        source .venv/bin/activate
      shell: bash
