version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(uv)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(github-actions)"
