/**
 * Converts a chrome.cookies.Cookie object into a Netscape cookie file line.
 *
 * Netscape format columns (tab-separated):
 *   domain  include_subdomains  path  secure  expires  name  value
 *
 * Netscape spec: a domain that starts with '.' matches subdomains and MUST
 * have include_subdomains=TRUE.  A domain without a leading dot is an exact
 * host match and MUST have include_subdomains=FALSE.  Chrome stores both
 * forms correctly, so we use the value as-is.
 */
function cookieToNetscape(cookie) {
  const domain = cookie.domain;
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = cookie.secure ? "TRUE" : "FALSE";

  // Session cookies have no expiry; use 0 as the sentinel value recognised
  // by tools such as curl / yt-dlp.
  const expires = cookie.expirationDate
    ? Math.floor(cookie.expirationDate)
    : 0;

  return [domain, includeSubdomains, cookie.path, secure, expires, cookie.name, cookie.value].join("\t");
}

/**
 * Fetches all cookies visible to the extension and returns them formatted
 * as a Netscape HTTP Cookie File string.
 */
async function buildNetscapeFile() {
  const cookies = await chrome.cookies.getAll({});

  const header = [
    "# Netscape HTTP Cookie File",
    "# https://curl.haxx.se/rfc/cookie_spec.html",
    "# This file was generated by the Cookie Exporter extension.",
    "",
  ].join("\n");

  const lines = cookies.map(cookieToNetscape);
  return header + lines.join("\n") + "\n";
}

// ── Download button ──────────────────────────────────────────────────────────

document.getElementById("exportBtn").addEventListener("click", async () => {
  const status = document.getElementById("status");
  status.textContent = "Collecting cookies…";

  try {
    const content = await buildNetscapeFile();

    // Encode as a data URL so we can pass it to chrome.downloads.download
    // without needing a service worker or a blob URL (which is not available
    // in Manifest V3 extension popups).
    const dataUrl =
      "data:text/plain;charset=utf-8," + encodeURIComponent(content);

    await chrome.downloads.download({
      url: dataUrl,
      filename: "cookies.txt",
      saveAs: false,
    });

    status.textContent = "Downloaded cookies.txt successfully.";
  } catch (err) {
    status.textContent = "Error: " + err.message;
  }
});

// ── Upload button ────────────────────────────────────────────────────────────

document.getElementById("uploadBtn").addEventListener("click", async () => {
  const status = document.getElementById("status");
  status.textContent = "Reading settings…";

  // Load server URL and API key from persistent storage.
  const {serverUrl, apiKey} = await chrome.storage.sync.get(["serverUrl", "apiKey"]);

  if (!serverUrl || !apiKey) {
    status.textContent = "Please configure the server URL and API key in Settings first.";
    return;
  }

  status.textContent = "Collecting cookies…";

  try {
    const content = await buildNetscapeFile();

    const blob = new Blob([content], {type: "text/plain"});
    const formData = new FormData();
    formData.append("file", blob, "cookies.txt");

    const response = await fetch(serverUrl, {
      method: "POST",
      headers: {
        Authorization: "Bearer " + apiKey,
      },
      body: formData,
    });

    if (response.ok) {
      status.textContent = "cookies.txt uploaded successfully.";
    } else {
      let detail = response.statusText;
      try {
        const json = await response.json();
        if (json.detail) detail = json.detail;
      } catch {
        // ignore parse errors
      }
      status.textContent = `Upload failed (${response.status}): ${detail}`;
    }
  } catch (err) {
    status.textContent = "Network error: " + err.message;
  }
});

// ── Settings link ────────────────────────────────────────────────────────────

document.getElementById("settingsLink").addEventListener("click", (e) => {
  e.preventDefault();
  chrome.runtime.openOptionsPage();
});
