name: CI/CD

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  lint-build-test:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        uv-version: ["0.7.12", "latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Python ${{ matrix.python-version }} with uv ${{ matrix.uv-version }}
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}
          uv-version: ${{ matrix.uv-version }}

      - name: Run Tests
        run: make test

      - name: Run linter
        run: make lint

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          flag-name: py ${{ matrix.python-version }} - uv ${{ matrix.uv-version }}

  finish:
    needs: lint-build-test
    runs-on: ubuntu-latest
    steps:
      - name: Finish Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: lint-build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/balaambot:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
