name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          export PYTHONUNBUFFERED=1
          pip install poetry

      - name: Install Dependencies
        run: make install

      - name: Check formatting with Ruff
        run: poetry run ruff format . --check --diff

      - name: Run Tests
        run: make test

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    needs: lint-build-test
    # Only run this job on pushes to the main branch
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/balaambot:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
