name: Ruff Linting and Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        uv-version: ["0.7.12", "latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }} with uv ${{ matrix.uv-version }}
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}
          uv-version: ${{ matrix.uv-version }}

      - name: Lint
        run: uv run ruff check --output-format=github .

  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        uv-version: ["0.7.12", "latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }} with uv ${{ matrix.uv-version }}
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}
          uv-version: ${{ matrix.uv-version }}

      - name: Format
        run: uv run ruff format . --check --diff
